String getDailyQuote() {
  List<String> quotes = [
    "It's okay not to be okay",
    "You are not your mental illness",
    "Your struggles do not define you",
    "Healing is not linear, but it is possible",
    "You are stronger than you realize",
    "Your mental health journey is unique to you",
    "Self-care is not selfish, it's necessary for good mental health",
    "Small steps can lead to big progress in mental health",
    "It's okay to ask for help",
    "You are not alone",
    "Your mental health matters",
    "You are worthy of love and happiness",
    "There is no shame in seeking help for your mental health",
    "You are capable of great things",
    "You are not your thoughts",
    "You are not your feelings",
    "Self-love is a journey, not a destination",
    "Progress is progress, no matter how small",
    "It's okay to take a break and rest",
    "You deserve kindness, especially from yourself",
    "Your feelings are valid",
    "Your mental health is just as important as your physical health",
    "Every day is a new opportunity for growth",
    "You have the strength to overcome any challenge",
    "Believe in yourself and your ability to heal",
    "Your story is important and deserves to be heard",
    "You are not defined by your past",
    "You are enough, just as you are",
    "There is hope, even in the darkest moments",
    "You are capable of creating positive change",
    "You are not alone in your struggles",
    "Your journey is unique and valuable",
    "Take things one step at a time",
    "You have the power to create a life you love",
    "You are worthy of respect and understanding",
    "Celebrate your progress, no matter how small",
    "Your worth is not determined by your productivity",
    "It's okay to set boundaries to protect your mental health",
    "You are deserving of love and compassion",
    "You are not a burden",
    "Your mistakes do not define you",
    "You are capable of overcoming obstacles",
    "Your challenges have made you stronger",
    "It's okay to prioritize your own needs",
    "You are deserving of happiness and fulfillment",
    "You have the courage to face difficult emotions",
    "Your voice matters, use it to advocate for yourself",
    "You are capable of creating a positive future",
    "You are not defined by your circumstances",
    "You have the power to change your life for the better",
    "Your journey to healing is valid and important",
    "You are resilient and can bounce back from setbacks",
    "Your worth is inherent and does not need to be earned",
    "You are not alone in your journey",
    "You are worthy of self-care and self-compassion",
    "You are capable of finding joy in everyday moments",
    "You are allowed to feel your emotions fully",
    "Your struggles have made you who you are",
    "You are not broken, you are healing",
    "You are deserving of forgiveness, especially from yourself",
    "Your experiences have value and can help others",
    "You are allowed to make mistakes and learn from them",
    "You are capable of creating the life you desire",
    "Your challenges are opportunities for growth",
    "You have the strength to overcome any obstacle",
    "You are deserving of love and belonging",
    "Your journey is unique and meaningful",
    "You are allowed to take breaks and rest when you need to",
    "You are worthy of acceptance and understanding",
    "You are not alone in your struggles, reach out for support",
    "You are resilient and can handle whatever comes your way",
    "You are capable of achieving your goals",
    "Your worth is not dependent on the opinions of others",
    "You are deserving of peace and happiness",
    "You are not defined by your past mistakes",
    "You have the power to create positive change in your life",
    "Your journey is a testament to your strength and resilience",
    "You are deserving of compassion, especially from yourself",
    "You are allowed to set boundaries to protect your well-being",
    "You are capable of overcoming any challenge that comes your way",
    "You are worthy of love and respect from yourself and others",
    "Your journey to healing is valid and important, take it one step at a time",
    "You are not alone, there are people who care about you and want to support you",
    "You are strong and resilient, you can face whatever challenges come your way",
    "You are capable of achieving your dreams, don't let fear hold you back",
    "You are worthy of happiness and fulfillment, don't settle for anything less",
    "You are not defined by your past, you have the power to create a bright future",
    "You are deserving of love and belonging, surround yourself with people who uplift you",
    "You are allowed to prioritize your own well-being, your needs matter",
    "You are capable of making a positive impact in the world, believe in your abilities",
    "You are not alone in your struggles, there are resources and support available to you",
    "You are resilient and can overcome any obstacles that come your way",
    "You are worthy of self-compassion, treat yourself with kindness and understanding",
    "You are not defined by your circumstances, you have the power to create change",
    "You are deserving of love and acceptance, both from yourself and others",
    "You are allowed to take time for yourself and engage in activities that bring you joy",
    "You are capable of growth and transformation, embrace the journey",
    "You are not alone, reach out for support when you need it",
    "You are strong and resilient, you can overcome any challenge",
    "You are deserving of happiness and fulfillment, pursue what brings you joy",
    "You are not defined by your past, you have the power to shape your future",
    "You are worthy of love and respect, both from yourself and others",
    "You are allowed to set boundaries and prioritize your own well-being",
    "You are capable of achieving your goals and living the life you desire",
    "You are not alone, there are people who care about you and want to see you succeed",
    "You are strong and resilient, you can overcome whatever challenges come your way",
    "You are deserving of love and belonging, surround yourself with people who uplift you",
    "You are not defined by your mistakes, you have the power to learn and grow",
    "You are worthy of self-compassion and forgiveness, treat yourself with kindness",
    "You are allowed to take breaks and rest when you need to, your well-being matters",
    "You are capable of creating positive change in your life and the world around you",
    "You are not alone, reach out for support when you need it, there are people who care",
    "You are strong and resilient, you have overcome challenges before and you can do it again",
    "You are deserving of happiness and fulfillment, pursue what brings you joy and fulfillment",
    "You are not defined by your past, you have the power to create a new future for yourself",
    "You are worthy of love and acceptance, both from yourself and from others",
    "You are allowed to prioritize your own well-being and set boundaries that protect it",
    "You are capable of achieving your goals and dreams, don't let doubt hold you back",
    "You are not alone, there are people who care about you and want to support you",
    "You are strong and resilient, you can overcome any challenges that come your way",
    "You are deserving of love and belonging, surround yourself with people who uplift you",
    "You are not defined by your mistakes, you have the power to learn and grow from them",
    "You are worthy of self-compassion and forgiveness, treat yourself with kindness and understanding",
    "You are allowed to take breaks and rest when you need to, your well-being matters",
    "You are capable of creating positive change in your life and in the world around you",
    "You are not alone, reach out for support when you need it, there are people who care about you",
    "You are strong and resilient, you have overcome challenges before and you can do it again",
    "You are deserving of happiness and fulfillment, pursue what brings you joy and fulfillment",
    "You are not defined by your past, you have the power to create a new future for yourself",
    "You are worthy of love and acceptance, both from yourself and from others",
    "You are allowed to prioritize your own well-being and set boundaries that protect it",
    "You are capable of achieving your goals and dreams, don't let doubt hold you back",
  ];

  DateTime now = DateTime.now();
  int dayOfYear = now.day; // Get the day of the year
  int index =
      dayOfYear % quotes.length; // Use the day of the year to select a quote

  return quotes[index];
}
